# https://taskfile.dev

version: "3"

tasks:
  generate:
    desc: Generate the language data
    cmds:
      - npm run generate

  build:
    desc: Build the VS Code extension
    cmds:
      - npm run build

  publish:
    desc: Build and publish the VS Code extension
    cmds:
      - task: build
      - task: publish:marketplace
      - task: publish:openvsx

  publish:marketplace:
    desc: Publish to the Visual Studio Marketplace
    prompt: Publish to the Visual Studio Marketplace?
    cmds:
      - npm run publish:marketplace

  publish:openvsx:
    desc: Publish to Open VSX
    prompt: Publish to Open VSX?
    cmds:
      - npm run publish:openvsx
